### ISSUE TITLE
Como persona en el ITAM encuentro las opciones de los platillos de forma sencilla.

### ISSUE THREAD

**Issue by paulinabustos** [ITAM-ADSI-2022/Proyecto-Meriyein#4]
Precondición:
- La persona se encuentra loggeada a la aplicación 

CA (Criterios de Aceptación):

- 

- [x] Después de log-earme a la aplicación o una pantalla que luce así 

![image](https://user-images.githubusercontent.com/6033705/160249806-d0d3ceb3-ecd2-49f6-85cb-538113e27270.png)

- 

- [x] La pantalla debe contener los subtitulos de "Desayunos" y "Comidas"
- [x] - Dentro de la cada sección deben visualizarse las fotografías correspondientes a la categoría en la tabla "Categorías" con el ID 1 para Desayunos y 2 para Comidas con un tamaño de 2px por 3 px. 
- [x] - El máximo de fotografías que debe verse por categoría deben ser 4
- [ ] - En caso de sobrepasar las 4 categorías se debe abrir una flecha de menú rotatorio a la derecha, debe verse de esta manera:

![image](https://user-images.githubusercontent.com/6033705/160250033-0f32fb99-1c48-475a-abb2-04828ba5f7d6.png)

**Comment by Axelord100** [comment]
Como estudiante en eco week quier poder pedir mi comida rápido y seguir estudiando

**Comment by Axelord100** [comment]
Como maestro quiero poder encontrar lo que quiero pedir rápido antes de la junta

**Comment by paulinabustos** [comment]
Después del Sprint Demo de 26 de Marzo, concluimos que aún falta este criterio de aceptación:

- [x] En caso de sobrepasar las 4 categorías se debe abrir una flecha de menú rotatorio a la derecha, debe verse de esta manera

Ya que haciendo una prueba con 5 elementos en una categoría, las fotografías se amontonaron.
